### ISSUE TITLE
invert Defects4J diffs

### ISSUE THREAD

**Issue by andre15silva** [ASSERT-KTH/repairbench-framework#68]
The diff files we are loading from Defects4J are inverted (i.e., the source file is the fixed version, and the target file is the buggy version).

This is not intuitive so we should invert them after loading.

https://github.com/ASSERT-KTH/elle-elle-aime/blob/e5b5e9669e87267b4b9fa358ee7ec39326f9b3b7/elleelleaime/core/benchmarks/defects4j/defects4j.py#L44-L47

**Comment by monperrus** [comment]
what about closing this issue?
